---
- name: SWAP用ファイルの作成
  shell: dd if=/dev/zero of=/swap.extended bs=1M count={{ SWAP.SIZE }}
  become: yes
  args:
    creates: /swap.extended
  register: result

- name: ファイルをSWAP化
  shell: mkswap /swap.extended
  become: yes
  when: result is changed

- name: SWAP領域として有効化
  shell: swapon /swap.extended
  become: yes
  when: result is changed
