---
- name: Install docker
  become: yes
  yum:
    name='docker'
    state=latest

- name: Service docker
  become: yes
  service:
    name=docker
    state=started
    enabled=yes

- name: Install docker-compose
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"

